name: Spring Boot CI/CD

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8 (for google-java-format compatibility)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Format Code with Google Java Format Action
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}


  build-and-test:
    runs-on: ubuntu-latest
    needs: format
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Report
        uses: 'actions/upload-artifact@v4'
        with:
          name: jacoco-report
          path: |
            ${{ github.workspace }}/target/site/jacoco/jacoco.xml
            ${{ github.workspace }}/target/site/jacoco/index.html

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          update-comment: true

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  health-check:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      SPRING_DATA_MONGODB_URI: mongodb://127.0.0.1:27017/EmployeeService
      FRONTEND_URL: http://localhost:3000
      BASE_URL: http://localhost:8082
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Download Built JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target

      - name: Start MongoDB Docker Container
        run: |
          docker run -d \
            --name mongodb \
            -p 27017:27017 \
            -v ${{ github.workspace }}/github-actions/mongodb:/docker-entrypoint-initdb.d \
            mongo:latest

      - name: Wait for MongoDB to be ready
        run: |
          echo "Waiting for MongoDB to start..."
          for i in $(seq 1 30); do
          # Attempt to connect to MongoDB. If successful, break the loop.
          # Using 'mongosh' or 'mongo' command inside the container to check status
          if docker exec mongodb mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1; then
           echo "MongoDB is ready!"
           break
          fi
          echo "Attempt $i/30: MongoDB not yet ready. Waiting 2 seconds..."
          sleep 2
          done
          # Final check: If MongoDB is still not ready after all attempts, fail the job.
          docker exec mongodb mongosh --eval "db.adminCommand('ping')" > /dev/null 2>&1 || \
          (echo "Error: MongoDB did not start in time." && exit 1)

      - name: Run Spring Boot application
        run: |
          echo "Starting Spring Boot application..."
          nohup java -jar target/*.jar  --spring.profiles.active=test &
          sleep 15 # Give the Spring Boot app enough time to start and connect to the database

          echo "Checking application health..."
          # Check the health endpoint. If it fails, the job will fail.
          curl -f ${{ env.BASE_URL }}/actuator/health || \
            (echo "Error: Spring Boot service not responding." && exit 1)
          echo "Spring Boot application is healthy."

      - name: Perform API Tests from Folder
        run: |
          API_TESTS_DIR="github-actions/api-tests"

          if [ -d "$API_TESTS_DIR" ]; then
            echo "Executing API tests from $API_TESTS_DIR..."
            find "$API_TESTS_DIR" -type f -name "*.sh" | sort | while read -r script; do
              echo "--- Running API Test: $(basename "$script") ---"
              chmod +x "$script" # Make sure the script is executable
              "$script" # Execute the script
              if [ $? -ne 0 ]; then # Check the exit code of the last command
                echo "Error: API Test $(basename "$script") failed!"
                exit 1 # Fail the GitHub Actions job
              fi
              echo "--- API Test $(basename "$script") completed successfully ---"
            done
            echo "All API tests completed."
          else
            echo "Warning: API tests directory '$API_TESTS_DIR' not found. Skipping API tests."
          fi

      - name: Clean up Spring Boot application
        if: always()
        run: |
          echo "Terminating Spring Boot application..."
          pkill -f 'java -jar'


      - name: Stop MongoDB Docker Container
        if: always()
        run: |
          echo "Stopping and removing MongoDB container..."
          docker stop mongodb && docker rm mongodb
